function flat(level)
	--[[local x, n
	for x = 1, numBgPones do
		spawn("BgPony" .. x, vector(x * 5, 0, 0))
	end ]]
	
	stands = spawn("BgStandsWithPhysics", vector(30, 0, 13.3))
	
	lyra = spawn("BgPonyLyra", vector(35.5, 1.5, 12))
	bonbon = spawn("BgPonyBonBon", vector(33, 1.5, 12.6))
	daisy = spawn("BgPonyDaisy", vector(16.5, -0.9, 13))
	sparkler = spawn("BgPonySparkler", vector(43, -0.9, 13.5))
	linky = spawn("BgPonyLinky", vector(28, 6, 6))
	carrot = spawn("BgPonyCarrot", vector(25, 3, 10))
	rose = spawn("BgPonyRose", vector(20, 0, 14.5))
	diamond = spawn("BgPonyDiamond", vector(45.5, -0.9, 14.5))
	lily = spawn("BgPonyLily", vector(13, -0.9, 13.5))
	cloudkicker = spawn("BgPonyCloudKicker", vector(10, 2, 10))
	flora = spawn("BgPonyFlora", vector(7, -0.9, 6.5))
	berry = spawn("BgPonyBerry", vector(30, 3, 10))
	cherry = spawn("BgPonyCherry", vector(49, -0.9, 15))
	sun = spawn("BgPonySun", vector(32, 8, 7))
	dizzy = spawn("BgPonyDizzy", vector(24, 7.5, 6.5))
	
	lyra:Sit()
	bonbon:Sit()
	daisy:Stand()
	daisy:Cheer()
	sparkler:Stand()
	sparkler:Cheer()
	linky:ChangeAnimation("Cheer2")
	carrot:Sit()
	carrot:Cheer()
	rose:Sit()
	diamond:Stand()
	lily:Stand()
	cloudkicker:Fly()
	flora:Stand()
	berry:Sit()
	cherry:Stand()
	sun:Fly()
	dizzy:Fly()
end
