function flat(level)
	--[[local x, n
	for x = 1, numBgPones do
		spawn("BgPony" .. x, vector(x * 5, 0, 0))
	end ]]
	
	stands = spawn("BgStandsWithPhysics", vector(30, 0, 3.3))
	
	--lyra = spawn("BgPonyLyra", vector(35.5, 1.5, 2))
	lyra = spawnBgPony("LyraSitting", vector(35.5, 1.5, 2.5))
	bonbon = spawnBgPony("BgPonyBonBon", vector(33, 1.5, 2.6))
	daisy = spawnBgPony("BgPonyDaisy", vector(16.5, -0.9, 3))
	sparkler = spawnBgPony("BgPonySparkler", vector(43, -0.9, 3.5))
	linky = spawnBgPony("BgPonyLinky", vector(28, 6, -4))
	carrot = spawnBgPony("BgPonyCarrot", vector(25, 3, 0))
	rose = spawnBgPony("BgPonyRose", vector(20, 0, 4.5))
	diamond = spawnBgPony("BgPonyDiamond", vector(45.5, -0.9, 4.5))
	lily = spawnBgPony("BgPonyLily", vector(13, -0.9, 3.5))
	cloudkicker = spawnBgPony("BgPonyCloudKicker", vector(10, 2, 0))
	flora = spawnBgPony("BgPonyFlora", vector(7, -0.9, -3.5))
	berry = spawnBgPony("BgPonyBerry", vector(30, 3, 0))
	cherry = spawnBgPony("BgPonyCherry", vector(49, -0.9, 5))
	sun = spawnBgPony("BgPonySun", vector(32, 8, -3))
	dizzy = spawnBgPony("BgPonyDizzy", vector(24, 7.5, -3.5))
	
	lyra:Sit()
	bonbon:Sit()
	daisy:Stand()
	daisy:Cheer()
	sparkler:Stand()
	sparkler:Cheer()
	linky:ChangeAnimation("Cheer2")
	carrot:Sit()
	carrot:Cheer()
	rose:Sit()
	diamond:Stand()
	lily:Stand()
	cloudkicker:Fly()
	flora:Stand()
	berry:Sit()
	cherry:Stand()
	sun:Fly()
	dizzy:Fly()
end
