//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ponykart.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("media/gui/")]
        public string MiyagiResourcesFileLocation {
            get {
                return ((string)(this["MiyagiResourcesFileLocation"]));
            }
            set {
                this["MiyagiResourcesFileLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("media/worlds/")]
        public string WorldFileLocation {
            get {
                return ((string)(this["WorldFileLocation"]));
            }
            set {
                this["WorldFileLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Level0")]
        public string MainMenuName {
            get {
                return ((string)(this["MainMenuName"]));
            }
            set {
                this["MainMenuName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("media/scripts/")]
        public string ScriptLocation {
            get {
                return ((string)(this["ScriptLocation"]));
            }
            set {
                this["ScriptLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("media/wheels/")]
        public string WheelFileLocation {
            get {
                return ((string)(this["WheelFileLocation"]));
            }
            set {
                this["WheelFileLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".luna")]
        public string LuaFileExtension {
            get {
                return ((string)(this["LuaFileExtension"]));
            }
            set {
                this["LuaFileExtension"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("media/scripts/levels/")]
        public string LevelScriptLocation {
            get {
                return ((string)(this["LevelScriptLocation"]));
            }
            set {
                this["LevelScriptLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("media/physicsmaterials/")]
        public string PhysicsMaterialFileLocation {
            get {
                return ((string)(this["PhysicsMaterialFileLocation"]));
            }
            set {
                this["PhysicsMaterialFileLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".physmat")]
        public string PhysicsMaterialFileExtension {
            get {
                return ((string)(this["PhysicsMaterialFileExtension"]));
            }
            set {
                this["PhysicsMaterialFileExtension"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(".wheel")]
        public string WheelFileExtension {
            get {
                return ((string)(this["WheelFileExtension"]));
            }
            set {
                this["WheelFileExtension"] = value;
            }
        }
    }
}
