function flat(level)
	--[[local x, n
	for x = 1, numBgPones do
		spawn("BgPony" .. x, vector(x * 5, 0, 0))
	end ]]
	
	stands = spawn("BgStandsWithPhysics", vector(6, 0, 0.66))
	
	lyra = spawnBgPony("LyraSitting", vector(7.1, 0.3, 0.5))
	bonbon = spawnBgPony("BgPonyBonBon", vector(6.6, 0.3, 0.52))
	daisy = spawnBgPony("BgPonyDaisy", vector(3.3, -0.18, 0.6))
	sparkler = spawnBgPony("BgPonySparkler", vector(8.6, -0.18, 0.7))
	linky = spawnBgPony("BgPonyLinky", vector(5.6, 1.2, -0.8))
	carrot = spawnBgPony("BgPonyCarrot", vector(5, 0.6, 0))
	rose = spawnBgPony("BgPonyRose", vector(4, 0, 0.9))
	diamond = spawnBgPony("BgPonyDiamond", vector(9.1, -0.18, 0.9))
	lily = spawnBgPony("BgPonyLily", vector(2.6, -0.18, 0.7))
	cloudkicker = spawnBgPony("BgPonyCloudKicker", vector(2, 0.4, 0))
	flora = spawnBgPony("BgPonyFlora", vector(1.4, -0.18, -0.7))
	berry = spawnBgPony("BgPonyBerry", vector(6, 0.6, 0))
	cherry = spawnBgPony("BgPonyCherry", vector(9.8, -0.18, 1))
	sun = spawnBgPony("BgPonySun", vector(6.4, 1.6, -0.6))
	dizzy = spawnBgPony("BgPonyDizzy", vector(4.8, 1.5, -0.7))
	
	lyra:Sit()
	bonbon:Sit()
	daisy:Stand()
	daisy:Cheer()
	sparkler:Stand()
	sparkler:Cheer()
	linky:ChangeAnimation("Cheer2")
	carrot:Sit()
	carrot:Cheer()
	rose:Sit()
	diamond:Stand()
	lily:Stand()
	cloudkicker:Fly()
	flora:Stand()
	berry:Sit()
	cherry:Stand()
	sun:Fly()
	dizzy:Fly()
	
	derpy = spawnDerpy(vector(0, 0, 0))
	derpy:ChangeAnimation("Hover1")
	derpy:AttachToKart(vector(-1, 1, 2), playerKart())
end
